#         ____                                                         ____  _            _
#  _   _|  _ \ ___  ___ ___  _ __ ___  _ __   ___ _ __  ___  __ _ ___|  _ \(_) __ _ _ __(_) __ _ ___
# | | | | |_) / _ \/ __/ _ \| '_ ` _ \| '_ \ / _ \ '_ \/ __|/ _` / __| | | | |/ _` | '__| |/ _` / __|
# | |_| |  _ <  __/ (_| (_) | | | | | | |_) |  __/ | | \__ \ (_| \__ \ |_| | | (_| | |  | | (_| \__ \
#  \__, |_| \_\___|\___\___/|_| |_| |_| .__/ \___|_| |_|___/\__,_|___/____/|_|\__,_|_|  |_|\__,_|___/
#  |___/                              |_|
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Configurações do servidor redis
redis:
  # Ativar a conexão com o redis
  enabled: false
  # Endereço de conexão. [EX: 127.0.0.1]
  host: 'localhost'
  # Porta de conexão. [EX: 3306]
  port: 6379
  # Usuário de conexão. [EX: root]
  username: ''
  # Senha do usuário de conexão: [EX: 123]
  password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20
# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
  enabled: true
  # Máximo que irá recolher por vez
  max: 1000

# Fechar o menu ao coletar a recompensa
close-menu-collect: false

# Sistema de npc
npc:
  skin: 'deliveryman'
  hologram:
    offset: 3.4
    hologram:
      - '&6&lRecompensas Diárias'
      - '&7Clique para coletar as entregas.'
      - '[item]DIAMOND'

# Sistema de lores
lore:
  chance: ['', '&6Chance: &f{chance}%', '']

# Tipos disponíveis:
# yPlugins -> Usa a formatação do yPlugins
# LETRA -> Força usar a formatação em letra
# NUMERO -> Força usar a formatação em número
format: 'yPlugins'