# Comandos e aliases do plugin
Comando:
  Mercador:
    Comando: 'mercador'
    Aliases: [ mercadores ]

# Opções gerais do plugin
Opcoes:
  # Maximo de itens por compra
  Maximo por compra: 64
  # Formatador de mensagens
  Formatador:
    Desconto: ' &7( {desconto}% )'

# Mensagens gerais do plugin
Mensagens:
  Permissao: '&cVocê não tem permissão para isto.'
  Lista: '&cMercadores disponíveis: &7{lista}&c.'
  Cancelou: '&cVocê cancelou a compra.'
  Nao e numero: '&cO argumento não é um número.'
  Maximo: '&cDesculpe, o valor máximo por compra é de {maximo}.'
  Inv cheio: '&cSeu inventário não tem espaço suficiente.'
  Nao possui: '&cVocê não possui a quantia &7{quantia} em &7{tipo}&c.'
  Cadastrado: '&cEste plugin &f{plugin}&c não está implementado no plugin de shop.'
  Desabilitado: '&cEste plugin &f{plugin}&c não está ligado.'
  Estoque: '&cEste item não possui esta quantia em estoque.'
  Forcou: '&aVocê forçou a vinda do mercador &7{mercador}.'
  ForcouSaida: '&aVocê forçou a saída do mercador &7{mercador}.'
  NaoChegou: '&cEste mercador ainda não chegou de viagem.'
  Ajuda: |
    &bComandos disponíveis:
    &b-> &3/mercador setmercador <mercador>
    &b-> &3/mercador delmercador <mercador>
    &b-> &3/mercador forcar <mercador> <duracao>
    &b-> &3/mercador forcarsaida <mercador>
    &b-> &3/mercador reload