#        __  __ _                 _____            _                 _          _       _     _
#  _   _|  \/  (_)_ __   __ _ ___| ____|_ __   ___| |__   __ _ _ __ | |_ ___   / \   __| | __| | ___  _ __
# | | | | |\/| | | '_ \ / _` / __|  _| | '_ \ / __| '_ \ / _` | '_ \| __/ __| / _ \ / _` |/ _` |/ _ \| '_ \
# | |_| | |  | | | | | | (_| \__ \ |___| | | | (__| | | | (_| | | | | |_\__ \/ ___ \ (_| | (_| | (_) | | | |
#  \__, |_|  |_|_|_| |_|\__,_|___/_____|_| |_|\___|_| |_|\__,_|_| |_|\__|___/_/   \_\__,_|\__,_|\___/|_| |_|
#  |___/
#

# Opções do FastAsyncWorldEdit ou WorldEdit (inclui AsyncWorldEdit)
FAWEOptions:
  Linear: true # -- do linear
  DestruidorInvertido: true # -- do destruidor invertido
  Esfera: true # -- da esfera
  X: true # -- do X