#         _     _          _
#  _   _| |   (_)_  _____(_)_ __ ___
# | | | | |   | \ \/ / _ \ | '__/ _ \
# | |_| | |___| |>  <  __/ | | | (_) |
#  \__, |_____|_/_/\_\___|_|_|  \___/
#  |___/
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

general:
  # Tempo para realizar a limpeza
  # em segundos
  time: 130
  # Limpar itens
  items: true
  # Limpar entidades
  entities: true
  # Não limpar entidades renomeadas
  blacklist-renamed: false
  # Não limpar entidades do AuraMobs
  blacklist-auramobs: false
  # Mundos que não serão limpos
  world-blacklist: []
  # Blacklist de items para não serem removidos
  items-blacklist:
    - 'BARRIER'
    - 'BEDROCK:0'
  # Blacklist de items que não serão limpar (com certa nbt-tag)
  items-nbt-tag-blacklist: []
  # Blacklist de entidades que não serão limpar
  entities-blacklist:
    - 'ARMOR_STAND'
    - 'ENDER_CRYSTAL'
    - 'FISHING_HOOK'
    - 'FALLING_BLOCK'
    - 'FIREBALL'
    - 'FIREWORK'
    - 'ITEM_FRAME'
    - 'LEASH_HITCH'
    - 'LIGHTNING'
    - 'PAINTING'
    - 'PRIMED_TNT'
    - 'SMALL_FIREBALL'
    - 'SPLASH_POTION'
    - 'THROWN_EXP_BOTTLE'
    - 'WEATHER'
  # Blacklist de entidades que não serão limpas (com certa nbt-tag)
  entities-nbt-tag-blacklist:
    - 'ySpawnersV2-Type'
    - 'yBossArena-Type'
    - 'yStackBosses-Type'
  # Blacklist de entidades que não serão limpas (com certa metadata)
  metadata-blacklist:
    - 'ySpawners-MobStacked'
    - 'ySpawnersV2-MobStacked'

# Limitador de entidades por Chunk
chunk-limiter:
  # Ativar o sistema
  enabled: false
  # Entidades que serão limitadas
  whitelist:
    - 'COW:10'

# Configuração dos sons
sounds:
  # Som que será enviado ao executar o /lixeiro
  command: 'NOTE_PLING'
  # Volume dos sons
  volume: 20
  # Volume de expansão dos sons
  pitch: 20
  # Sons que serão enviados a cada x tempo
  timer:
    - '120,NOTE_STICKS'
    - '60,NOTE_STICKS'
    - '30,NOTE_STICKS'
    - '10,NOTE_STICKS'
    - '5,NOTE_STICKS'
    - '4,NOTE_STICKS'
    - '3,NOTE_STICKS'
    - '2,NOTE_STICKS'
    - '1,NOTE_STICKS'
    - '0,NOTE_PLING'

# Configurações das mensagens temporizadas
message-timer:
  # Mensagem que irá ser enviada no chat
  # Utilize <nl> para uma nova linha (Mini-Messages permitido)
  chat:
    - '120, &eTodos os itens no chão serão removidos em 2 minutos!<nl> &8♻ &fPara visualizar o tempo, digite &7/lixeiro&f.'
    - '60, &eTodos os itens no chão serão removidos em 1 minuto!<nl> &8♻ &fPara visualizar o tempo, digite &7/lixeiro&f.'
    - '10, &eTodos os itens no chão serão removidos em 10 segundos!'
    - '5, &eTodos os itens no chão serão removidos em 5 segundos!'
    - '4, &eTodos os itens no chão serão removidos em 4 segundos!'
    - '3, &eTodos os itens no chão serão removidos em 3 segundos!'
    - '2, &eTodos os itens no chão serão removidos em 2 segundos!'
    - '1, &eTodos os itens no chão serão removidos em 1 segundo!'
    - '0, &eForam removidos &e&l{total}&e itens do chão!'
  # Mensagem que irá ser enviada no actionbar
  actionbar:
    - '120, &eTodos os itens no chão serão removidos em 2 minutos!'
    - '60, &eTodos os itens no chão serão removidos em 1 minuto!'
    - '30, &eTodos os itens no chão serão removidos em 30 segundos!'
    - '10, &eTodos os itens no chão serão removidos em 10 segundos!'
    - '5, &eTodos os itens no chão serão removidos em 5 segundos!'
    - '4, &eTodos os itens no chão serão removidos em 4 segundos!'
    - '3, &eTodos os itens no chão serão removidos em 3 segundos!'
    - '2, &eTodos os itens no chão serão removidos em 2 segundos!'
    - '1, &eTodos os itens no chão serão removidos em 1 segundo!'
    - '0, &eForam removidos &e&l{total}&e itens do chão!'
  # Titles que serão enviados a cada x segundos
  # Utilize <nl> para uma nova linha
  title:
    - '30,&eLixeiro<nl>&7Limpando em 30 segundos.'
    - '10,&eLixeiro<nl>&7Limpando em 10 segundos.'
    - '0,&eLixeiro<nl>&7{total} itens limpos.'