Database:
  Tipo: SQLITE #Tipos: MYSQL, SQLITE
  IP: localhost:3306
  DB: test
  User: admin
  Pass: ''
  Debug: true

# Comando e aliases do plugin
Comando:
  Comando: 'hunter'
  Aliases: [ ]

# Opcoes de configuração do NPC
NPC:
  ID: 923287
  # Para puxar a SKIN do TOP(1) deixe vazio
  Skin: 'TheThunderGod063'
  Holograma:
    Altura: 3.1
    Holograma:
      - '&6Matador de aluguel'
      - '&7Veja as recompensas disponíveis.'

# Tipo de formatos de quantia disponíveis: LETRA (K,M,B,T...) e NUMERO (100,00)
Formatacao: 'LETRA'

# Ativar a troca do sistema de chat quando estiver no mohist
# compatível apenas com: UltimateChat, nChat e Legendchat
mohist-chat: false

# Opções gerais do plugin
Opcoes:
  # Permissão para poder receber a recompensa de matar o jogador
  KillPerm: ''
  Minimo colocar: 1000.0 # minimo de money para pagar pela morte do jogador
  Minimo tirar: 10000.0 # minimo de money para o morto perder ( x % do seu money )
  Maximo tirar: 20000.0 # máximo de money para o morto perder ( x % do seu money )
  Porcentagem tirar: 10.0 # quando o jogador que estiver sendo caçado morrer, perder esta % de money
  Porcentagem adicionar: 5.0 # quando o jogador que estiver sendo caçado matar um jogador, aumentar essa % na recompensa
  # Mundos onde os eventos de matar e morrer não serão contabilizados
  Mundos blacklist:
    - 'guerra'
    - 'eventos'

# Mensagens gerais do plugin
Mensagens:
  Permissao: '&cVocê não tem permissão para isto.'
  Cancelou: '&cVocê cancelou a ação.'
  Nao encontrado: '&cJogador não encontrado.'
  Deslogou: '&cAparentemente este jogador deslogou.'
  Nao e numero: '&cO argumento não é um número.'
  Minimo: '&cO valor mínimo é &71K&c.'
  Nao possui: '&cVocê não possui esta quantia de dinheiro.'
  Si mesmo: '&cVocê não pode pagar pela sua própria morte.'
  Colocou: '&aVocê está agora pagando &eR${money} &apela cabeça do jogador &e{player}&a.'
  Colocou ativar: false #ativa a mensagem de cima
  Perdeu: '&cVocê perdeu 10% do seu money por morrer com uma recompensa pela sua morte.'
  Coletou: '&aVocê ganhou &eR${money} &aao matar o jogador &e{player}&a.'
  Coletou ativar: false #ativa a mensagem de cima
  Staff: '&cVocê não pode definir valores pela morte de um staff.'
  Setado: '&aNPC da pesca setado com sucesso.'
  Removido: '&aNPC da pesca removido com sucesso'
  Nao setado: '&cO NPC não está setado.'
  Digite:
    - ''
    - '&aDigite o nome do jogador.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''
  Digite valor:
    - ''
    - '&aDigite o preço pela cabeça do jogador.'
    - '&7para cancelar digite &ncancelar&7.'
    - ''

Anuncios:
  Colocou:
    Actionbar:
      Ativar: true
      Msg: '&aFoi colocado &e{money}&a pela morte do jogador &e{player}&a.'
    Title:
      Ativar: true
      Broadcast: false
      Title: '&aMate o &e{player}'
      Subtitle: '&ae ganhe &e{money}&a.'
    Chat:
      Ativar: true
      Broadcast: false
      Msg:
        - '&aFoi colocado &e{money}&a pela morte do jogador &e{player}&a.'
  Coletou:
    Actionbar:
      Ativar: true
      Msg: '&e{matou} &aganhou &e{money} &apor matar o jogador &e{morreu}&a.'
    Title:
      Ativar: true
      Broadcast: false
      Title: '&e{matou} &aganhou &e{money}'
      Subtitle: '&aao matar &e{morreu}&a.'
    Chat:
      Ativar: true
      Broadcast: false
      Msg:
        - '&e{matou} &aganhou &e{money} &apor matar o jogador &e{morreu}&a.'
  Somou:
    Actionbar: '&e{matou} &aaumentou em &e{money} &asua recompensa de procurado ao matar &e{morreu}&a.'
    Title: '&e{matou} &aaumentou em &e{money}<nl>&asua recompensa de procurado'
    Chat: [ '&e{matou} &aaumentou em &e{money} &asua recompensa de procurado ao matar &e{morreu}&a.' ]

Setas:
  Voltar:
    CustomSkull: false
    URL: ''
    ID: ARROW
    Data: 0
    Glow: true
    Name: '&cVoltar'
    Lore:
      - ''
      - '&7Clique para voltar.'
      - ''
  Proximo:
    CustomSkull: false
    URL: ''
    ID: ARROW
    Data: 0
    Glow: true
    Name: '&aPróximo'
    Lore:
      - ''
      - '&7Clique para ir à próxima página.'
      - ''

Formats:
  - ''
  - ''
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'O'
  - 'N'
  - 'D'