#         ____  _             _
#  _   _|  _ \(_)_ __   __ _| |_ __ _
# | | | | |_) | | '_ \ / _` | __/ _` |
# | |_| |  __/| | | | | (_| | || (_| |
#  \__, |_|   |_|_| |_|\__,_|\__\__,_|
#  |___/
#
# Modo de depuração para correção de problemas no plugin.
debug-mode: false
